version: '3'

services:

  app:
    image: 'jc21/nginx-proxy-manager:latest'
    ports:
      - '80:80'
      - '81:81'
      - '443:443'
    environment:
      DB_MYSQL_HOST: "db"
      DB_MYSQL_PORT: 3306
      DB_MYSQL_USER: "someuser"
      DB_MYSQL_PASSWORD: "supersecret"
      DB_MYSQL_NAME: "dbname"
    volumes:
      - ./path/to/data:/data
      - ./letsencrypt:/etc/letsencrypt
    restart: unless-stopped
    
  db:
    image: 'jc21/mariadb-aria:latest'
    environment:
      MYSQL_ROOT_PASSWORD: 'supersecret'
      MYSQL_DATABASE: 'dbname'
      MYSQL_USER: 'someuser'
      MYSQL_PASSWORD: 'supersecret'
    volumes:
      - /path/to/data:/var/lib/mysql
    restart: unless-stopped