version: "3.2"

services:

  sonarr:
    container_name: sonarr
    image: ghcr.io/hotio/sonarr:latest
    restart: unless-stopped
    logging:
      driver: json-file
    network_mode: bridge
    ports:
      - 8989:8989
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America\Chicago
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /path/to/data:/config
      - /path/to/data:/data
