version: "2.1"

services:

  qbittorrent:
    container_name: qbittorrent
    image: hotio/qbittorrent
    network_mode: bridge
    ports:
      - 8282:8080
    environment:
      - PUID=1000
      - PGID=1000
      - UMASK=002
      - TZ=America\Chicago
    volumes:
      - /path/to/data:/config
      - /path/to/data:/downloads
    restart: unless-stopped
