version: "2.1"

services:

  ombi:
    image: lscr.io/linuxserver/ombi
    container_name: ombi
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Chicago
    volumes:
      - /path/to/data:/config
    ports:
      - 3579:3579
    restart: unless-stopped