version: "2.1"

services:

  readarr:
    image: ghcr.io/linuxserver/readarr:nightly
    container_name: readarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America\Chicago
    volumes:
      - /path/to/data:/config
      - /path/to/data:/data 
    ports:
      - 8787:8787
    restart: unless-stopped