version: "3.2"

services:

  jackett:
    image: linuxserver/jackett
    container_name: jackett
    restart: unless-stopped
    ports:
      - 9117:9117
    volumes:
      - /path/to/data:/config
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America\Chicago
    