server:
  http_listen_port: 9080
  grpc_listen_port: 0
positions:
  filename: /tmp/positions.yaml
clients:
  - url: http://example.com:3100/loki/api/v1/push
scrape_configs:
  - job_name: computer-system
    static_configs:
    - targets:
        - localhost
      labels:
        job: computer-varlogs
        container: computer
        __path__: /var/log/*log